model_name: distil_v1
result_dir: /root/infer_test/A100-infer_results/data/infer/distil_v1/
mig_profile_id: 0
fixed_time: True
batch_size: 256

dcgm:
  exc_path: /root/A100-benchmark/dcgm_recorder.py
  group_id: 2
  instance_id: 0
  save_dir: /root/A100-benchmark/data/infer/resnet50_moco/
hydra:
  run:
    dir: /root/infer_test/logs/infer/distil_v1/${now:%Y-%m-%d}/${now:%H-%M-%S}