model_name: vision_transformer
result_dir: /root/A100-benchmark/data/cv_infer/
fixed_time: 60
batch_size: 256
data_path: /root/places365_standard/
workers: 6
gpu: 0
defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
hydra:
  output_subdir: null
  run:
    dir: .