model_name: vision_transformer
result_dir: /root/A100-benchmark/data/cv_train/
fixed_time: 120
batch_size: 256
data_path: /root/places365_standard/
workers: 6
gpu: 0
optimizer:
  lr: 1e-5
  momentum: 0.9
  weight_decay: 1e-4
defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
hydra:
  output_subdir: null
  run:
    dir: .