model_name: vision_transformer
result_dir: /root/A100-benchmark/data/train/cv/
mig_profile: disable
fixed_time: 120
batch_size: 256
data_path: /root/places365_standard/
workers: 6
gpu: 0
optimizer:
  lr: 1e-5
  momentum: 0.9
  weight_decay: 1e-4
hydra:
  run:
    dir: /root/A100-benchmark/logs/train/cv/${now:%Y-%m-%d}/${now:%H-%M-%S}