arch: vision_transformer
feature_extract: False
num_classes: 365
workers: 6
data_path: /root/TorchScene/places365_standard/
batch_sizes: [8]
lr: 1e-5
momentum: 0.9
device: cuda:0
hydra:
  run:
    dir: /root/infer_test/logs/finetune/${now:%Y-%m-%d}/${now:%H-%M-%S}