arch: resnet50
moco_dim: 128
moco_k: 65536
moco_m: 0.999
moco_t: 0.07
mlp: None
lr: 0.015
seed: None
data: /root/places365_standard/
workers: 32
aug_plus: True
momentum: 0.9
weight_decay: 1e-4
fixed_time: True
gpu: 0
mig_profile_id: 0
result_dir: /root/A100-benchmark/data/train/resnet50_moco/
batch_sizes: [8,16,32,64,128,256]
dcgm:
  exc_path: /root/A100-benchmark/dcgm_recorder.py
  group_id: 2
  instance_id: 0
  save_dir: /root/A100-benchmark/data/train/resnet50_moco/

hydra:
  run:
    dir: /root/A100-benchmark/logs/train/resnet50_moco/${now:%Y-%m-%d}/${now:%H-%M-%S}