arch: vision_transformer
moco_dim: 128
moco_k: 65536
moco_m: 0.999
moco_t: 0.07
mlp: None
multiprocessing_distributed: False
gpu: None
lr: 0.015
world_size: 1
seed: None
dist_url: tcp://224.66.41.62:23456
data: /root/TorchScene/places365_standard/
batch_size: 256
workers: 32
aug-plus: True
momentum: 0.9
weight_decay: 1e-4
fix_time: True
distributed: False