arch: resnet50
moco_dim: 128
moco_k: 65536
moco_m: 0.999
moco_t: 0.07
mlp: None
lr: 0.015
seed: None
data: /root/TorchScene/places365_standard/
batch_size: 256
workers: 32
aug-plus: True
momentum: 0.9
weight_decay: 1e-4
fix_time: True