model_name: bert-base
result_dir: /root/A100-benchmark/data/train/nlp/
mig_profile: disable
fixed_time: 120
seq_length: 64
batch_size: 32
workers: 6
gpu: 0
optimizer:
  lr: 1e-5
  momentum: 0.9
  weight_decay: 1e-4
hydra:
  run:
    dir: /root/A100-benchmark/logs/train/nlp/${now:%Y-%m-%d}/${now:%H-%M-%S}