model_name: bert-base
result_dir: /root/A100-benchmark/data/nlp_train/
fixed_time: 60
seq_length: 64
batch_size: 32
workers: 6
gpu: 0
optimizer:
  lr: 1e-5
  momentum: 0.9
  weight_decay: 1e-4
defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
hydra:
  output_subdir: null
  run:
    dir: .