model_name: vision_transformer
gpuID: 0
workload: cv_infer
save_dir: /root/A100-benchmark/data/cv_infer/
mig_profiles: ['1g.10gb', '2g.20gb', '3g.40gb', '4g.40gb', '7g.80gb']
hydra:
  run:
    dir: /root/MIGProfiler/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
dcgm:
  save_dir: /root/A100-benchmark/data/cv_infer/
